# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dca138ea6bb8f147c865d9964ea91370c170f0a14513ec178071b1eda54b5fef7f2dae248823e1a899834e2afcf536cf410ab5a05d24486e393223a3d74d7c7

test:
  secret_key_base: f5c4aab175dcdf201d06e1379c00d0ac6c0dabb5ab433cc830a4cf58fb1eff9444c2d0be53b8bcca096d7316b3de3b72894bc382cad84b22e055168c2f77b4b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
